// Code generated by protoc-gen-go. DO NOT EDIT.
// source: builder.proto

package sidecar

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildRequest struct {
	SourcePath           string   `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	MetadataPath         string   `protobuf:"bytes,2,opt,name=metadata_path,json=metadataPath,proto3" json:"metadata_path,omitempty"`
	OutputPath           string   `protobuf:"bytes,3,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildRequest) Reset()         { *m = BuildRequest{} }
func (m *BuildRequest) String() string { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()    {}
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a5e6cb4f7c8dc9, []int{0}
}

func (m *BuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest.Unmarshal(m, b)
}
func (m *BuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest.Marshal(b, m, deterministic)
}
func (m *BuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest.Merge(m, src)
}
func (m *BuildRequest) XXX_Size() int {
	return xxx_messageInfo_BuildRequest.Size(m)
}
func (m *BuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest proto.InternalMessageInfo

func (m *BuildRequest) GetSourcePath() string {
	if m != nil {
		return m.SourcePath
	}
	return ""
}

func (m *BuildRequest) GetMetadataPath() string {
	if m != nil {
		return m.MetadataPath
	}
	return ""
}

func (m *BuildRequest) GetOutputPath() string {
	if m != nil {
		return m.OutputPath
	}
	return ""
}

type BuildResponse struct {
	// Types that are valid to be assigned to Message:
	//	*BuildResponse_StandardOut
	//	*BuildResponse_StandardError
	Message              isBuildResponse_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *BuildResponse) Reset()         { *m = BuildResponse{} }
func (m *BuildResponse) String() string { return proto.CompactTextString(m) }
func (*BuildResponse) ProtoMessage()    {}
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a5e6cb4f7c8dc9, []int{1}
}

func (m *BuildResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResponse.Unmarshal(m, b)
}
func (m *BuildResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResponse.Marshal(b, m, deterministic)
}
func (m *BuildResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResponse.Merge(m, src)
}
func (m *BuildResponse) XXX_Size() int {
	return xxx_messageInfo_BuildResponse.Size(m)
}
func (m *BuildResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResponse proto.InternalMessageInfo

type isBuildResponse_Message interface {
	isBuildResponse_Message()
}

type BuildResponse_StandardOut struct {
	StandardOut string `protobuf:"bytes,1,opt,name=standard_out,json=standardOut,proto3,oneof"`
}

type BuildResponse_StandardError struct {
	StandardError string `protobuf:"bytes,2,opt,name=standard_error,json=standardError,proto3,oneof"`
}

func (*BuildResponse_StandardOut) isBuildResponse_Message() {}

func (*BuildResponse_StandardError) isBuildResponse_Message() {}

func (m *BuildResponse) GetMessage() isBuildResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *BuildResponse) GetStandardOut() string {
	if x, ok := m.GetMessage().(*BuildResponse_StandardOut); ok {
		return x.StandardOut
	}
	return ""
}

func (m *BuildResponse) GetStandardError() string {
	if x, ok := m.GetMessage().(*BuildResponse_StandardError); ok {
		return x.StandardError
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BuildResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BuildResponse_StandardOut)(nil),
		(*BuildResponse_StandardError)(nil),
	}
}

func init() {
	proto.RegisterType((*BuildRequest)(nil), "sidecar.BuildRequest")
	proto.RegisterType((*BuildResponse)(nil), "sidecar.BuildResponse")
}

func init() { proto.RegisterFile("builder.proto", fileDescriptor_68a5e6cb4f7c8dc9) }

var fileDescriptor_68a5e6cb4f7c8dc9 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x1b, 0x45, 0x43, 0x27, 0x89, 0x87, 0x05, 0x45, 0xbc, 0x54, 0xda, 0x83, 0x9e, 0x82,
	0xe8, 0xc5, 0x73, 0x44, 0xe8, 0x4d, 0xc9, 0x0b, 0x94, 0x69, 0x77, 0x30, 0x05, 0xdb, 0x8d, 0x3b,
	0x33, 0xef, 0x2f, 0xd9, 0x49, 0x44, 0x7a, 0x5b, 0xbe, 0xfd, 0x98, 0x7f, 0xfe, 0x81, 0x6a, 0xab,
	0xfb, 0x6f, 0x4f, 0xb1, 0xee, 0x63, 0x90, 0xe0, 0x72, 0xde, 0x7b, 0xda, 0x61, 0x5c, 0x2a, 0x94,
	0xcd, 0xf0, 0xd3, 0xd2, 0x8f, 0x12, 0x8b, 0x5b, 0x40, 0xc1, 0x41, 0xe3, 0x8e, 0x36, 0x3d, 0x4a,
	0x77, 0x9b, 0xdd, 0x67, 0x8f, 0xf3, 0x16, 0x0c, 0x7d, 0xa2, 0x74, 0x6e, 0x05, 0xd5, 0x81, 0x04,
	0x3d, 0x0a, 0x9a, 0x72, 0x96, 0x94, 0x72, 0x82, 0x49, 0x5a, 0x40, 0x11, 0x54, 0x7a, 0x15, 0x53,
	0xce, 0x6d, 0x8a, 0xa1, 0x41, 0x58, 0x76, 0x50, 0x8d, 0xb1, 0xdc, 0x87, 0x23, 0x93, 0x5b, 0x41,
	0xc9, 0x82, 0x47, 0x8f, 0xd1, 0x6f, 0x82, 0x8a, 0x05, 0xaf, 0x67, 0x6d, 0x31, 0xd1, 0x0f, 0x15,
	0xf7, 0x00, 0x57, 0x7f, 0x12, 0xc5, 0x18, 0xa2, 0x85, 0xaf, 0x67, 0x6d, 0x35, 0xf1, 0xf7, 0x01,
	0x37, 0x73, 0xc8, 0x0f, 0xc4, 0x8c, 0x5f, 0xf4, 0xfc, 0x06, 0x79, 0x63, 0xd5, 0xdd, 0x2b, 0x5c,
	0xa4, 0xa7, 0xbb, 0xae, 0xc7, 0xfa, 0xf5, 0xff, 0xee, 0x77, 0x37, 0xa7, 0xd8, 0x76, 0x7b, 0xca,
	0xb6, 0x97, 0xe9, 0x6a, 0x2f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0x2c, 0x77, 0x1f, 0x46,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BuilderClient is the client API for Builder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuilderClient interface {
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (Builder_BuildClient, error)
}

type builderClient struct {
	cc *grpc.ClientConn
}

func NewBuilderClient(cc *grpc.ClientConn) BuilderClient {
	return &builderClient{cc}
}

func (c *builderClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (Builder_BuildClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Builder_serviceDesc.Streams[0], "/sidecar.Builder/Build", opts...)
	if err != nil {
		return nil, err
	}
	x := &builderBuildClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Builder_BuildClient interface {
	Recv() (*BuildResponse, error)
	grpc.ClientStream
}

type builderBuildClient struct {
	grpc.ClientStream
}

func (x *builderBuildClient) Recv() (*BuildResponse, error) {
	m := new(BuildResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BuilderServer is the server API for Builder service.
type BuilderServer interface {
	Build(*BuildRequest, Builder_BuildServer) error
}

// UnimplementedBuilderServer can be embedded to have forward compatible implementations.
type UnimplementedBuilderServer struct {
}

func (*UnimplementedBuilderServer) Build(req *BuildRequest, srv Builder_BuildServer) error {
	return status.Errorf(codes.Unimplemented, "method Build not implemented")
}

func RegisterBuilderServer(s *grpc.Server, srv BuilderServer) {
	s.RegisterService(&_Builder_serviceDesc, srv)
}

func _Builder_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BuilderServer).Build(m, &builderBuildServer{stream})
}

type Builder_BuildServer interface {
	Send(*BuildResponse) error
	grpc.ServerStream
}

type builderBuildServer struct {
	grpc.ServerStream
}

func (x *builderBuildServer) Send(m *BuildResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Builder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sidecar.Builder",
	HandlerType: (*BuilderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Build",
			Handler:       _Builder_Build_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "builder.proto",
}
