name: Temporarily Skipped Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Temporary Pass
        run: echo "Workflow skipped for now"

  # unit-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.23.x
  #     - name: Run unit tests
  #       run: make unit-tests

  # checks:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.23.x
  #     - name: Run checks
  #       run: make checks

  # gosec:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.23.x
  #     - name: Run gosec
  #       run: make gosec

  # build-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.23.x
  #     - name: Build and push image
  #       run: |
  #         make image
  #         make image-push
